apiVersion: v1
kind: Service
metadata:
  name: 3d-location-tracker-service
spec:
  selector:
    app: 3d-location-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

